### ISSUE TITLE
CI Integration

### ISSUE THREAD

**Issue by FlorianWendelborn** [davestewart/alias-hq#26]
Is there any way to set-up `alias-hq` CLI as a CI tool?

Basically, I’d want to use GitLab pipelines to run `alias-hq` and fail if a path alias is not used, to enforce that the entire project always uses them.

So, the requirements would be:

1. Run some sort of command (e.g. `yarn run alias-hq --check`)
2. Command uses exit code 1 if some issue was found
3. Command uses exit code 0 if no issue was found

Thanks for the tool BTW, really useful and well-done

**Comment by davestewart** [comment]
Hey Florian,

Thanks for the kind words!

So I don't know much about CLI / Pipelines, but if I understand you correctly, you'd like to:

- reuse the existing (or have similar) codemod functionality which trawls the `import` statements of a project
- to check they always use aliases rather than local paths (or, at least adhere to the logic that the shortest path is used)
- and have this exposed via the command line and pass or fail in a manner than is appropriate for a build pipeline tool

I haven't worked on this for a good few months, but I don't see why that wouldn't be possible.

I don't have much time at the moment, which is a problem (I have an existing PR for renaming aliases which I've not touched in months too!)

I'd be happy for you to submit a PR though. The codemod side of things is surprisingly straightforward; I'd be happy to help you if you needed it.

**Comment by davestewart** [comment]
Looking at file which sets up the source transforms:

- https://github.com/davestewart/alias-hq/blob/master/cli/modules/source/transformer/transformer.js#L41

If `newPath` is returned, it means the import / require could be simplified, so I presume at this point you would want to exit with code 1.

One of the surprisingly challenging bits of this project was working out how best to ask questions and how best to preview and report results, so I suspect you might also want to think about that, rather than just exiting?

**Comment by davestewart** [comment]
Any more interest in this @FlorianWendelborn or should I close the issue?

**Comment by FlorianWendelborn** [comment]
@davestewart I’d say neither. I don’t have the time right now to develop this, but I still think it’s a useful/vital piece of what this software should be able to do. I’d hope that tagging it as `Help Wanted`, one day someone will have time to submit a PR.

**Comment by davestewart** [comment]
Sure. I'm also busy, but I'll leave this open and maybe find time to do it when I need a break from something else!

**Comment by davestewart** [comment]
Closing as stale / not high priority. Feel free to reopen!
